# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_REGULATOR_S2DOS05)		+= s2dos05-regulator.o
s2dos05-regulator-$(CONFIG_REGULATOR_S2DOS05)	+= s2dos05.o s2dos05_powermeter.o

ccflags-$(CONFIG_REGULATOR_DEBUG) += -DDEBUG

