obj-$(CONFIG_EPEN_WACOM_W9020) += w9020.o
w9020-y := wacom_i2c.o wacom_i2c_sec.o wacom_i2c_elec.o w9020_flash.o

obj-$(CONFIG_EPEN_WACOM_W9021) += w9021.o
w9021-y := wacom_i2c.o wacom_i2c_sec.o wacom_i2c_elec.o w9020_flash.o

obj-$(CONFIG_EPEN_WACOM_WEZ01) += wez01.o
wez01-y := wacom_i2c.o wacom_i2c_sec.o wacom_i2c_elec.o wez01_flash.o

ccflags-y += -Wformat
